# Introduction aux probabilités

Le but de cette première séance est de découvrir Python et de l’utiliser pour simuler des variables aléatoires discrètes. 

## 1 Installation et premiers pas

1. Anaconda (voir https://www.anaconda.com/distribution/) est pratiquement incontournable de nos jours. C’est une distribution gratuite, libre, et optimisée pour Python qui repose sur Conda. En particulier Anaconda permet de gérer les dépendances entre les librairies Python de manière automatique.

2. Jupyter notebook : c’est l’outil recommandé pour ce cours. Cela lance une interface dans votre navigateur (Firefox, Chrome, etc.). De plus ces fichiers peuvent être visualisés en ligne facilement (en les mettant sur un site comme github par exemple).

3. On peux installer les packages utilisables par 
```
pip install <package name>
```

In [8]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable
     |████████████████████████████████| 12.3 MB 5.1 MB/s 
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


## 2 Les bases du Python

Depuis Jupyter Notebook, vous pouvez exécuter toutes les commandes déjà disponibles et même définir vos propres fonctions, mais avant d’en arriver là nous allons d’abord nous familiariser avec les commandes de base de Python.

In [ ]:
5

In [ ]:
5 * 10

In [ ]:
a = 5
b = 10
a / b

In [ ]:
a = 10
b = 3
print(a+b, a-b)

In [ ]:
# valeur alphanumérique
a = 'TP'
b = 'proba'
print(a + b)

In [ ]:
# valeurs booléennes
0 < 1

In [ ]:
5 * 10 >= 6 * 10

In [ ]:
# list
a = [1, 2, 3 , 4]
a

On peut aussi définir les vecteurs en utilisant numpy.

Le module numpy est utilisé dans presque tous les projets de calcul numérique sous
Python. Il fournit des structures de données performantes pour la manipulation de vecteurs,
matrices et tenseurs.

In [9]:
import numpy as np

In [ ]:
np.pi

In [ ]:
np.e

In [ ]:
# Vecteur: l'argument est une liste Python
liste = [1, 3, 2, 4]
vecteur = np.array(liste)
print(vecteur)
print(vecteur[0])

In [ ]:
print(type(vecteur))

In [ ]:
print(np.shape(vecteur))

In [ ]:
a = np.arange(10)
a

In [ ]:
# le slicing d'un vecteur 
a[2:9:3] # [début:fin:pas]

In [ ]:
a[2:8:3] # le dernier élément n'est pas inclus

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a*b)
print(np.dot(a,b))

Voir ce lien pour l'information plus détaillée : http://math.mad.free.fr/depot/numpy/base.html

## 3. Function

Un grand nombre de fonctions sont disponibles, présentes dans le module de base ou dans des bibliothèques séparées. Elles peuvent avoir zéro, un ou plusieurs arguments, et renvoient un vecteur ou un objet de structure plus élaborée.

In [ ]:
np.arange(2, 20, 3)  #  cette fonction permet de construire des suites de nombres équidistants

In [ ]:
a = np.array([1, 4, 2, 3])
np.sort(a) # cette fonction renvoie un vecteur dont les coordonnées sont celles de v après un tri croissant ou décroissant

In [ ]:
np.sum(a) # cette fonction effectue la somme des coordonnées du vecteur

In [ ]:
print(a) # cette fonction permet d’afficher le vecteur v

In [189]:
from numpy import random
random.randint(5, size = 10) # cette fonction permet de générer un nombre aléatoire entier

array([4, 1, 2, 4, 0, 1, 1, 4, 1, 4])

In [190]:
random.choice([1,3,5,7,9],size=3,replace=False) # cette fonction nous permet de faire un tirage

array([3, 9, 7])

In [ ]:
# Il est possible aussi de créer ses propres fonctions

def my_function(a,b):
    c = 1/a + 1/b
    d = a + b
    return c*d

In [ ]:
my_function(1,2)

## Exercice

Ex1:

Écrire une commande qui renvoie le résultat
    - du lancer d’un dé
    - du lancer de 2 dés
    - de la somme des résultats du lancer de 2 dés
    - du tirage du loto (5 numéros parmi 49)

In [208]:
from numpy import random
des = random.randint(1, 7)
print("Résulat un dès : ", des)

doubleDes = random.randint(1,7, size = 2)
print("Résultat deux dès : ",doubleDes)

resDeuxDes = doubleDes[0] + doubleDes[1]
print("La somme des deux dès vaut : ", resDeuxDes)

loto = [i for i in range (1, 50)]
resLoto = random.choice(loto, size=5, replace = False)
print(resLoto)

Résulat un dès :  1
Résultat deux dès :  [3 4]
La somme des deux dès vaut :  7
[48 25  5 30  4]


Ex2: 

Créer une fonction **Urne** à trois arguments $k,p,q$ qui modélise le tirage sans remise de $k$ boules dans un sac contenant $p$ boules rouges et $q$ boules noires. \
Indication : voici un exemple de sortie :

```
Urne(6,8,5)

Output:
"Rouge" "Noire" "Noire" "Rouge" "Rouge" "Rouge"
```

In [211]:
from numpy import random

def urne(k,p,q):
    liste = p*["Rouge"] + q*["Noire"]
    print(random.choice(liste, size = k, replace=False))


urne(8,4,4)

['Rouge' 'Rouge' 'Rouge' 'Noire' 'Noire' 'Noire' 'Noire' 'Rouge']


Ex3:
    
Lorsqu’on effectue $n$ tirages indépendants d’une même expérience aléatoire, on appelle fréquence empirique du résultat $k$ le rapport entre le nombre de fois où $k$ est tiré, et $n$. Exemple : on jette à $7$ reprises un dé, avec pour résultats $1, 1, 5, 2, 6, 5, 3$ ; la fréquence empirique de $5$ est $2/7$, celle de $4$ est $0$.

Écrire une fonction **FreqEmp** à un paramètre $n$ qui renvoie la fréquence empirique de $5$ lors de n tirages indépendants d’un dé à six faces. Comparer les fréquences empiriques pour $n = 10$, $n = 100$ puis $n = 1000$, avec la probabilité (théorique) de tirer un $5$ lorsqu’on lance un dé.

In [212]:
from numpy import random

# Pour la valeur 5
def freqEmp(n):
    val = 0
    L = random.randint(1,7,size = n)
    val = collections.Counter(L)
    print(val[5],"/",len(L))

freqEmp(10)
freqEmp(100)
freqEmp(1000)

2 / 10
18 / 100
157 / 1000


Ex4:

Trouvez une fonction qui permette de définir une matrice et utilisez-la pour construire la matrice

$$
\left(\begin{array}
10 & 0 & 3\\
0 & 5 & 4\\
3 & 2 & 5
\end{array}\right)
$$ 

In [124]:
def mat(n, p):
    if n <= 0 or p <= 0:
        print("Erreur, une des valeurs est négative !")
        return
    mat = [[0 for j in range (p)]for i in range(n)]

    return mat

def afficheMat(mat):
    for i in range(len(mat)):
        print(mat[i])

mat = mat(3,3)
mat[0][0] = 10
mat[0][2] = 3
mat[1][1] = 5
mat[1][2] = 4
mat[2][0] = 3
mat[2][1] = 2
mat[2][2] = 5
print(afficheMat(mat))

[10, 0, 3]
[0, 5, 4]
[3, 2, 5]
None
